### ISSUE TITLE
ld: framework not found DeckLinkAPI

### ISSUE THREAD

**Issue by lklepner** [Streampunk/macadam#6]
Hi! 

I'm very excited to have found this project but I'm having trouble installing/compiling it. 

I'm on a Mac 10.11.6 with the latest version of Xcode 8.2.1, Blackmagic_Desktop_Video_10.8.5 and the latest node-gyp installed. 

----
$ npm install --save macadam

> macadam@0.2.6 install /srv/electron-demo/node_modules/macadam
> node-gyp rebuild

  CXX(target) Release/obj.target/macadam/src/macadam.o
  CXX(target) Release/obj.target/macadam/src/Capture.o
  CXX(target) Release/obj.target/macadam/src/Playback.o
  SOLINK_MODULE(target) Release/macadam.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
ld: framework not found DeckLinkAPI
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/macadam.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

---

It seems like the error, as I read it, is relating to not finding the DeckLinkAPI? binding.gyp seems to point at /Library/Frameworks/DeckLinkAPI.framework ... and looking in the corresponding location I see files. 

Can you give me some pointers to get up and running?

**Comment by sparkpunkd** [comment]
Not sure why it is not linking OK on Mac but I've not checked recently as my primary development platform is Windows. You are not doing anything wrong. I'm travelling at the moment but when I'm back in my office  in a few days time - where my Mac is - I'll try and build it.

**Comment by lklepner** [comment]
Thanks for the feedback. My primary dev box is a mac but I'm really targeting Win7 so I've started digging into that. 

I'm finding that getting the C++ compiler up and running is no small task. At first I installed Visual Studio 2017 andthen  ran into errors which seemed to be linked to node-gyp not supporting 2017 yet.. so I installed Visual Studio 2015 and the error has changed ("failed to locate CL.exe") which I'm troubleshooting now but I'm afraid I might have mucked things up by installing VS 2015 alongside VS 2017 rather than uninstalling VS2017 first. I might end up wiping this machine and starting over.. 

Can you provide any additional insight into how best to get things up and running on Win7?

**Comment by sparkpunkd** [comment]
Best thing to do is follow the instructions for node-gyp .... see https://github.com/nodejs/node-gyp and follow the Windows-specific instructions.

**Comment by lklepner** [comment]
Got it - many thanks! My test hardware, a decklink duo 2, is due to arrive later today. I hope to begin testing with it tomorrow.

**Comment by sparkpunkd** [comment]
Checked the compile of Mac. Seems to be OK on 10.11.6, Xcode 7.3.1. Make sure the BlackMagic Desktop Video is installed before attempting to compile.

Download Desktop Video from https://www.blackmagicdesign.com/nl/support

**Comment by buraktt** [comment]
Hi,
If all prerequisites are installed and you're still getting linker error (framework not found DeckLinkAPI) make sure Xcode command line tools are installed:

`xcode-select --install`
