### ISSUE TITLE
Key & fill support

### ISSUE THREAD

**Issue by florisporro** [Streampunk/macadam#8]
Does this support key & fill if a bmdFormat8BitARGB or bmdFormat8BitBGRA format is supplied?

If not, where would be the appropriate place to add it in?

**Comment by sparkpunkd** [comment]
Key and fill support is now being worked on and should be released in a new version in early November.

**Comment by sparkpunkd** [comment]
[Keying](/Streampunk/macadam/#keying) (key and fill support) is now available from version 2.0.3 onwards.
