### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by navelencia** [Streampunk/macadam#9]
Hi! Really like where your project is going and I'm trying to install it on my machine. However, I can't install it because of a build issue. I've already installed "native" modules on my machine and I haven't encountered a problem like that. 

See the gist with the console output and error once running the npm install.
https://gist.github.com/navelencia/619f6b92654ede20713f0370d34b79d6

I'm running Windows 10 x64. Thanks a lot for your help!

**Comment by sparkpunkd** [comment]
What version of Node are you building with? We are making use of the N-API and functions only available from some of the later versions of Node v8 and then Node v10. The errors refer to those functions.
